.github/workflows/django.yml

Add django tests to automatically run django tests.

Continuous Integration

---

CHANGELOG.md
CONTRIBUTE

* Add a changelog.
* Add instructions on how to contribute #18 (#19)

CONTRIBUTE, CHANGELOG

---

CHANGELOG.md
CONTRIBUTE

* Add a changelog.
* Add instructions on how to contribute #18 (#19)

Bump version (#20)

---

project/accounts/templates/login.html
project/accounts/templates/register.html
project/templates/base.html

feat(templates) add a base.html template to extends from

---

project/carpool/models.py

Fields added:
- name: CharField
- nbPlaces: IntegerField
- couleur: CharField

Add Vehicle model (issue #14)

---

project/carpool/templates/rides/list.html

J'ai pas la vision créative donc j'ai fait le plus basique

Better empty rides list with CTA to create a new ride #74

---

project/accounts/views/profile.py
project/templates/base.html
project/templates/messages/container.html
project/templates/messages/script.html
project/templates/messages/toast.html

Django Messages Framework Integration

---

project/carpool/tests/factories.py
project/chat/tests/factories.py
project/chat/tests/test_views.py
project/chat/views.py
project/project/celery.py
pyproject.toml

Tests 100% coverage for chat app

---

project/project/settings/production.py
project/project/urls.py
project/templates/base.html
project/templates/includes/navbar.html

language selection

---

project/carpool/templates/rides/detail.html
project/chat/locale/fr/LC_MESSAGES/django.po
project/chat/templates/chat/includes/mod_profile.html
project/chat/templates/chat/includes/sidebar.html
project/chat/templates/chat/index.html
project/chat/templates/chat/moderation/index.html
project/chat/templates/chat/moderation/room.html
project/chat/templates/chat/moderation/search.html
project/chat/templates/chat/room.html

translations for chat

---

project/accounts/locale/fr/LC_MESSAGES/django.po
project/carpool/locale/fr/LC_MESSAGES/django.po
project/carpool/templates/rides/list.html
project/chat/locale/LC_MESSAGES/django.po

Fix (#164) departure arrival grey on rides list

---

project/carpool/forms.py
project/carpool/locale/fr/LC_MESSAGES/django.po
project/carpool/templates/rides/create.html

Add translation for ride_create view

---

project/chat/templates/chat/room.html

Fix using insecure ws instead of wss with https

---

project/accounts/locale/fr/LC_MESSAGES/django.po
project/accounts/templates/registration/login.html

i18n inclusion in french for username field

---

project/carpool/forms.py
project/carpool/templates/rides/create.html
project/carpool/templates/rides/edit.html

Set maximum price per seat at 999 €

---

project/carpool/views.py

Filter out rides that are in the past

---

project/project/settings/production.py
project/project/urls.py
project/templates/base.html

favicons and logs in production settings

---

project/accounts/locale/fr/LC_MESSAGES/django.po
project/accounts/tasks.py
project/accounts/templates/account/data_export_email.txt
project/accounts/templates/registration/verify_email/emails/verify_email.txt
project/carpool/locale/fr/LC_MESSAGES/django.po
project/chat/locale/fr/LC_MESSAGES/django.po
project/chat/tasks.py
project/chat/templates/chat/emails/unread_messages.txt
project/locale/fr/LC_MESSAGES/django.po
project/templates/emails/consent_footer.txt
project/templates/emails/mandatory_footer.txt

- fix #241 
- fix #240 
- for #28

Improved emails and translation

---

.env.dist
project/locale/fr/LC_MESSAGES/django.po
project/project/context_processors.py
project/project/settings/production.py
project/templates/includes/navbar.html

Report Issue button to contact support

---

project/chat/templates/chat/includes/sidebar.html
project/chat/templates/chat/includes/sidebar_item.html
project/chat/views.py

Pagination for chats
